# Generated by Django 5.0.3 on 2024-03-11 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lalg_compile_exps',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lalg_interp_exps',
        ),
    ]
